pipeline:
  name: webo cicd
  identifier: webo_cicd
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  template:
    templateRef: service_cicd
    versionLabel: v1
    templateInputs:
      properties:
        ci:
          codebase:
            connectorRef: github
            repoName: k8s-cicd
            build: <+input>
      stages:
        - stage:
            identifier: build
            type: CI
            spec:
              execution:
                steps:
                  - step:
                      identifier: build_and_test
                      template:
                        templateInputs:
                          type: Run
                          spec:
                            connectorRef: dockerhub
                            image: node:22-alpine
                            command: |-
                              cd app
                              node --test
                  - step:
                      identifier: build_and_push
                      template:
                        templateInputs:
                          type: BuildAndPushDockerRegistry
                          spec:
                            connectorRef: dockerhub
                            repo: wealthbot/harness-lab-app
                            dockerfile: app/Dockerfile
                            context: app
        - stage:
            identifier: deploy_dev
            template:
              templateInputs:
                type: Deployment
                spec:
                  service:
                    serviceRef: webo_money_world
        - stage:
            identifier: deploy_prod
            template:
              templateInputs:
                type: Deployment
                spec:
                  service:
                    serviceRef: webo_money_world
